# Generated by Django 3.2.7 on 2021-12-28 14:55

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Astronaut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('brief', models.TextField(default='')),
                ('birthdate', models.DateField()),
                ('country', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('active_duty', models.BooleanField(default=False)),
                ('time_in_space', models.IntegerField(default=0)),
                ('total_evas', models.IntegerField(default=0)),
                ('total_eva_time', models.IntegerField(default=0)),
                ('retirement_date', models.DateField(blank=True)),
                ('wikipedia_url', models.URLField()),
                ('photo', models.ImageField(blank=True, upload_to='astronauts/')),
            ],
        ),
        migrations.CreateModel(
            name='AstronautImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('astronaut', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='astronauts.astronaut')),
            ],
        ),
    ]
