# Generated by Django 3.2.7 on 2021-12-28 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astronauts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('brief', models.TextField(default='')),
                ('photo', models.ImageField(blank=True, upload_to='missions/')),
                ('type', models.CharField(max_length=255)),
                ('cospar_id', models.CharField(max_length=255)),
                ('satcat_no', models.CharField(max_length=255)),
                ('duration', models.DurationField()),
                ('distance_traveled', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('launch_site', models.CharField(max_length=255)),
                ('landing_site', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='astronaut',
            name='death',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='astronaut',
            name='rank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='astronaut',
            name='selection',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='MissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('mission', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='astronauts.mission')),
            ],
        ),
    ]
