# Generated by Django 3.2.7 on 2021-12-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronauts', '0002_auto_20211228_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='astronaut',
            name='missions',
            field=models.ManyToManyField(to='astronauts.Mission'),
        ),
        migrations.AddField(
            model_name='mission',
            name='wikipedia_url',
            field=models.URLField(default=''),
        ),
    ]
