# Generated by Django 3.2.7 on 2021-12-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronauts', '0007_auto_20211228_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronaut',
            name='time_in_space',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
