# Generated by Django 3.2.7 on 2021-12-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronauts', '0008_alter_astronaut_time_in_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronaut',
            name='retirement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
