# Generated by Django 4.0 on 2022-01-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronauts', '0010_alter_astronaut_total_eva_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='crew',
            field=models.ManyToManyField(blank=True, to='astronauts.Astronaut'),
        ),
    ]
