
nationalities = {
    "Afghan":"Afghanistan",
    "African":"Africa",
    "Algerian":"Algeria",
    "American":"United States",
    "Antiguans":"Antigua And Barbuda",
    "Argentine":"Argentina",
    "Argentinean":"Argentina",
    "Argentinian":"Argentina",
    "Argentino":"Argentina",
    "Armenian":"Armenia",
    "Aussie":"Australia",
    "Australian":"Australia",
    "Australianb":"Australia",
    "Australien":"Australia",
    "Austrian":"Austria",
    "Soviet": "USSR",
    "French": "France",
    "Spanish": "Spain",
    "German": "Germany",
    "Italian": "Italy",
    "Japanse": "Japan",
    "Chinese": "China",
    "Canadian": "Canada",
    "British": "UK",
    "Russian": "Russia",
    "Ukrainian": "Ukraine",
    "Soviet Union": "USSR",
    "United States": "USA",
    "Soviet (formerly)Russian": "USSR",
    "Soviet/Russian": "USSR",
    "Soviet / Russian": "USSR",
    "Soviet Union Russia": "USSR",
    "Belarusian": "Belarusia",
    "Polish": "Poland",
    "Bulgarian": "Bulgaria",
    "Cuban": "Cuba",
    "Soviet / Ukrainian": "USSR",
    "Australian-American": "USA",
}

def nationality_to_country(demonym):
    return nationalities[demonym.replace(u'\xa0', u' ').strip()]